name: Demo Exemplo WebApp

on: workflow_dispatch

env:
  AZURE_WEBAPP: '.'
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build 
      run: dotnet build --configuration Release --no-restore

    - name: dotnet publish
      run: dotnet publish -c Release -o ${{ env.AZURE_WEBAPP }}/output

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: artifact
        path: output/

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: iac
        path: Infraestrutura/

  deploy-IaC:
    needs: build
    name: Deploy Infra
    runs-on: ubuntu-latest
    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: iac
        path: '${{ github.workspace }}//Infraestrutura'

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v1
      with:
        scope: resourcegroup 
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: Labs
        template: Infraestrutura/deploy.json
        deploymentMode: Incremental

  deploy:
    needs: deploy-IaC
    name: Deploy Web App
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: artifact
        path: ${{ env.AZURE_WEBAPP }}/output

    - name: Azure Login
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Deploy to Azure WebApp'
      uses: azure/webapps-deploy@v2
      with:
        app-name: Demo-githubactions02
        package: ${{ env.AZURE_WEBAPP }}/output
